function generateData(startDate, blocks) {
    let data = [];
    let date = new Date(startDate);
    const incrementDate = (date) => {
        let newDate = new Date(date);
        newDate.setDate(date.getDate() -1);
        return newDate.toISOString().split('T')[0];
    };

        blocks.forEach((block) => {
            let newBlock = { ...block };
            newBlock.fecha = incrementDate(date);
            date = new Date(newBlock.fecha);
            data = data.concat(newBlock);
        });
    return data;
}

const initialData = [
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-07",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-08",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-09",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-10",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-11",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-12",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-13",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-14",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-15",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-16",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-17",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-18",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-19",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-20",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-21",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-22",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-23",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-24",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-25",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-26",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-27",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-28",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-29",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-30",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2024-12-31",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-01",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-02",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-03",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-04",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-05",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-06",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-07",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-08",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-09",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-10",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-11",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-12",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-13",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-14",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-15",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-16",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-17",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-18",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-19",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-20",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-21",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-22",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-23",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-24",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-25",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-26",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-27",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-28",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-29",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-30",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-01-31",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-01",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-02",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-03",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-04",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-05",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-06",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-07",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-08",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-09",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-10",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-11",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-12",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-13",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-14",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-15",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-16",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-17",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-18",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-19",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-20",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-21",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-22",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-23",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-24",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-25",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-26",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-27",
        "temperatura_maxima": 18.2,
        "temperatura_minima": 17.8,
        "temperatura_media": 18,
        "humedad_maxima": 96,
        "humedad_minima": 74,
        "humedad_media": 85,
        "horas_hr_mayor_que_90": 9.3,
        "hr_mayor_que_90_max": 18.2,
        "hr_mayor_que_90_min": 17.8,
        "hr_mayor_que_90_med": 18,
        "precipitacion": 29,
        "velocidad_del_viento": 26,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-02-28",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-03-01",
        "temperatura_maxima": 21,
        "temperatura_minima": 19,
        "temperatura_media": 20,
        "humedad_maxima": 92,
        "humedad_minima": 72,
        "humedad_media": 82,
        "horas_hr_mayor_que_90": 8,
        "hr_mayor_que_90_max": 21,
        "hr_mayor_que_90_min": 19,
        "hr_mayor_que_90_med": 20,
        "precipitacion": 27,
        "velocidad_del_viento": 34,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-03-02",
        "temperatura_maxima": 23,
        "temperatura_minima": 18,
        "temperatura_media": 20.5,
        "humedad_maxima": 93,
        "humedad_minima": 72,
        "humedad_media": 82.5,
        "horas_hr_mayor_que_90": 7.5,
        "hr_mayor_que_90_max": 23,
        "hr_mayor_que_90_min": 18,
        "hr_mayor_que_90_med": 20.5,
        "precipitacion": 26.8,
        "velocidad_del_viento": 37,
        "estacion": 10
    },
    {
        "estacion_codigo": "002",
        "estacion_nombre": "La Loma",
        "fecha": "2025-03-03",
        "temperatura_maxima": 18.5,
        "temperatura_minima": 16.5,
        "temperatura_media": 17.5,
        "humedad_maxima": 97,
        "humedad_minima": 77,
        "humedad_media": 87,
        "horas_hr_mayor_que_90": 9.7,
        "hr_mayor_que_90_max": 18.5,
        "hr_mayor_que_90_min": 16.5,
        "hr_mayor_que_90_med": 17.5,
        "precipitacion": 28,
        "velocidad_del_viento": 34,
        "estacion": 10
    }
];

const newData = generateData("2024-11-5", initialData);
console.log(newData);
